/***********************************/
/*Author: Shehab emad*/
/*Version 1.0*/
/*Data:19/8/2020*/
/**************************************/

#ifndef NVIC_CONFIG_H
#define NVIC_CONFIG_H


/* OPTIONS:
MNVIC_GROUP_4_SUB0
MNVIC_GROUP_3_SUB1
MNVIC_GROUP_2_SUB2
MNVIC_GROUP_1_SUB3
MNVIC_GROUP_0_SUB4
*/

#define MNVIC_GROUP_SUB_DISTRIBUTION 		MNVIC_GROUP_2_SUB2


#if MNVIC_GROUP_SUB_DISTRIBUTION==MNVIC_GROUP_4_SUB0
	#define GROUP_PRIORITY_MAX 			15
	#define SUB_PRIORITY_MAX			0
#elif  MNVIC_GROUP_SUB_DISTRIBUTION==MNVIC_GROUP_3_SUB1
	#define GROUP_PRIORITY_MAX 			7
	#define SUB_PRIORITY_MAX			2
#elif  MNVIC_GROUP_SUB_DISTRIBUTION==MNVIC_GROUP_2_SUB2
	#define GROUP_PRIORITY_MAX 			4
	#define SUB_PRIORITY_MAX			4
#elif  MNVIC_GROUP_SUB_DISTRIBUTION==MNVIC_GROUP_1_SUB3
	#define GROUP_PRIORITY_MAX 			2
	#define SUB_PRIORITY_MAX			7
#elif  MNVIC_GROUP_SUB_DISTRIBUTION==MNVIC_GROUP_0_SUB4
	#define GROUP_PRIORITY_MAX 			0
	#define SUB_PRIORITY_MAX			15
#else
	/*Error*/
#endif

#endif
